Borrow some TravisCI libass-related setup from sassc gem

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -2,4 +2,33 @@
 
 set -e
 
+if [ -z "$SASSC_PATH" ]; then
+  export SASSC_PATH=`pwd`
+fi
+
+if [ -f "$SASSC_PATH/sassc/sassc.c" ]; then
+  export SASSC_PATH=$SASSC_PATH/sassc
+elif [ -f "$SASSC_PATH/../sassc.c" ]; then
+  export SASSC_PATH=$SASSC_PATH/..
+fi
+
+if [ ! -f "$SASSC_PATH/sassc.c" ]; then
+  echo "SassC source directory not found"
+  echo "Consider setting it via SASSC_PATH"
+  echo "Or call this script from the root"
+  unset SASSC_PATH && exit 1
+fi
+
+if [ -z "$SASS_LIBSASS_PATH" ]; then
+  export SASS_LIBSASS_PATH="$SASSC_PATH/../libsass/"
+  echo "SASS_LIBSASS_PATH env-variable missing"
+  echo "Using default: $SASS_LIBSASS_PATH"
+fi
+
+if [ ! -d "$SASS_LIBSASS_PATH" ]; then
+  git clone https://github.com/sass/libsass.git "$SASS_LIBSASS_PATH"
+else
+  echo "LibSass source directory exists, skiping Git Clone"
+fi
+
 bundle install "$@"
